import z from 'zod'

export const destinationSchema = z.object({
  name: z.string().min(1, 'Name is required'),
  slug: z.string().min(1, 'Slug is required').regex(/^[a-z0-9-]+$/, 'Slug must be kebab-case'),
  county: z.string().min(1, 'County is required'),
  locality: z.string().optional().default(''),
  category: z.string().min(1, 'Category is required'),
  status: z.enum(['draft', 'published', 'archived']).default('draft'),
  latitude: z.number().optional().default(0),
  longitude: z.number().optional().default(0),
  mapLabel: z.string().optional().default(''),
  accessRoute: z.string().optional().default(''),
  distanceReference: z.string().optional().default(''),
  shortDescription: z.string().optional().default(''),
  fullDescription: z.string().optional().default(''),
  significance: z.string().optional().default(''),
  history: z.string().optional().default(''),
  thingsToDo: z.string().optional().default(''),
  suitableAudiences: z.string().optional().default(''),
  duration: z.string().optional().default(''),
  difficulty: z.enum(['easy', 'moderate', 'hard']).default('easy'),
  seasonality: z.string().optional().default(''),
  indicativeFees: z.string().optional().default(''),
  openingInfo: z.string().optional().default(''),
  transportNotes: z.string().optional().default(''),
  accessibility: z.array(z.string()).optional().default([]),
  facilities: z.string().optional().default(''),
  safetyNotes: z.string().optional().default(''),
  heroImageUrl: z.string().optional().default(''),
  heroCaption: z.string().optional().default(''),
  heroCredit: z.string().optional().default(''),
  heroAlt: z.string().optional().default(''),
  gallery: z.array(z.object({
    url: z.string(),
    caption: z.string().optional().default(''),
    credit: z.string().optional().default(''),
    alt: z.string().optional().default(''),
    rightsStatus: z.string().optional().default(''),
  })).optional().default([]),
  videoUrl: z.string().optional().default(''),
  videoCaption: z.string().optional().default(''),
  videoCredit: z.string().optional().default(''),
  nearbyAttractions: z.string().optional().default(''),
  associatedEvents: z.string().optional().default(''),
  associatedStories: z.string().optional().default(''),
  associatedCourses: z.string().optional().default(''),
  associatedConservation: z.string().optional().default(''),
  source: z.string().optional().default(''),
  contentOwner: z.string().optional().default(''),
  verificationStatus: z.enum(['verified', 'unverified', 'pending']).default('pending'),
  curationFlags: z.object({
    trending: z.boolean().default(false),
    hiddenGem: z.boolean().default(false),
  }).optional().default({ trending: false, hiddenGem: false }),
})

export type DestinationInput = z.input<typeof destinationSchema>
export type DestinationOutput = z.output<typeof destinationSchema>
