/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAiConfigRouteImport } from './routes/_authenticated/ai-config'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedConservationRouteImport } from './routes/_authenticated/conservation'
import { Route as AuthenticatedDestinationsRouteImport } from './routes/_authenticated/destinations'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedLmsRouteImport } from './routes/_authenticated/lms'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAiConfigRoute = AuthenticatedAiConfigRouteImport.update({
  id: '/ai-config',
  path: '/ai-config',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConservationRoute =
  AuthenticatedConservationRouteImport.update({
    id: '/conservation',
    path: '/conservation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDestinationsRoute =
  AuthenticatedDestinationsRouteImport.update({
    id: '/destinations',
    path: '/destinations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLmsRoute = AuthenticatedLmsRouteImport.update({
  id: '/lms',
  path: '/lms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-config': typeof AuthenticatedAiConfigRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/conservation': typeof AuthenticatedConservationRoute
  '/destinations': typeof AuthenticatedDestinationsRoute
  '/events': typeof AuthenticatedEventsRoute
  '/lms': typeof AuthenticatedLmsRoute
  '/media': typeof AuthenticatedMediaRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-config': typeof AuthenticatedAiConfigRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/conservation': typeof AuthenticatedConservationRoute
  '/destinations': typeof AuthenticatedDestinationsRoute
  '/events': typeof AuthenticatedEventsRoute
  '/lms': typeof AuthenticatedLmsRoute
  '/media': typeof AuthenticatedMediaRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ai-config': typeof AuthenticatedAiConfigRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/conservation': typeof AuthenticatedConservationRoute
  '/_authenticated/destinations': typeof AuthenticatedDestinationsRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/lms': typeof AuthenticatedLmsRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/no-access'
    | '/reset-password'
    | '/ai-config'
    | '/analytics'
    | '/campaigns'
    | '/conservation'
    | '/destinations'
    | '/events'
    | '/lms'
    | '/media'
    | '/users'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/no-access'
    | '/reset-password'
    | '/ai-config'
    | '/analytics'
    | '/campaigns'
    | '/conservation'
    | '/destinations'
    | '/events'
    | '/lms'
    | '/media'
    | '/users'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/no-access'
    | '/reset-password'
    | '/_authenticated/ai-config'
    | '/_authenticated/analytics'
    | '/_authenticated/campaigns'
    | '/_authenticated/conservation'
    | '/_authenticated/destinations'
    | '/_authenticated/events'
    | '/_authenticated/lms'
    | '/_authenticated/media'
    | '/_authenticated/users'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NoAccessRoute: typeof NoAccessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ai-config': {
      id: '/_authenticated/ai-config'
      path: '/ai-config'
      fullPath: '/ai-config'
      preLoaderRoute: typeof AuthenticatedAiConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conservation': {
      id: '/_authenticated/conservation'
      path: '/conservation'
      fullPath: '/conservation'
      preLoaderRoute: typeof AuthenticatedConservationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/destinations': {
      id: '/_authenticated/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof AuthenticatedDestinationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lms': {
      id: '/_authenticated/lms'
      path: '/lms'
      fullPath: '/lms'
      preLoaderRoute: typeof AuthenticatedLmsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAiConfigRoute: typeof AuthenticatedAiConfigRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedConservationRoute: typeof AuthenticatedConservationRoute
  AuthenticatedDestinationsRoute: typeof AuthenticatedDestinationsRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedLmsRoute: typeof AuthenticatedLmsRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiConfigRoute: AuthenticatedAiConfigRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedConservationRoute: AuthenticatedConservationRoute,
  AuthenticatedDestinationsRoute: AuthenticatedDestinationsRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedLmsRoute: AuthenticatedLmsRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NoAccessRoute: NoAccessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
